"""add payment reservation model

Revision ID: ad1ed231c93f
Revises: eac8e72faf91
Create Date: 2024-06-10 19:42:51.054287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad1ed231c93f'
down_revision: Union[str, None] = 'eac8e72faf91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=4), nullable=False),
    sa.Column('amount', sa.REAL(), nullable=False),
    sa.Column('by_user', sa.Integer(), nullable=False),
    sa.Column('reservation', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['by_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reservation'], ['reservation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###
