"""updated reservation model

Revision ID: 6bea3f303f1c
Revises: ad1ed231c93f
Create Date: 2024-06-10 20:05:22.383909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bea3f303f1c'
down_revision: Union[str, None] = 'ad1ed231c93f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('amount', sa.REAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'amount')
    # ### end Alembic commands ###
