"""add seed

Revision ID: eac8e72faf91
Revises: 774c3e405abf
Create Date: 2024-06-05 16:33:07.295879

"""
from typing import Sequence, Union
from migrations.seed import seed_data
import asyncio

# revision identifiers, used by Alembic.
revision: str = 'eac8e72faf91'
down_revision: Union[str, None] = '774c3e405abf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    loop = asyncio.get_event_loop()
    loop.run_until_complete(seed_data())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
