"""Added columns to stations

Revision ID: edf9d2897932
Revises: d1ac0b8e13ca
Create Date: 2024-05-23 21:20:04.262853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf9d2897932'
down_revision: Union[str, None] = 'd1ac0b8e13ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pc_station', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('pc_station', sa.Column('is_working', sa.Boolean(), nullable=True))
    op.add_column('ps_station', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('ps_station', sa.Column('is_working', sa.Boolean(), nullable=True))
    op.add_column('vr_station', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('vr_station', sa.Column('is_working', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vr_station', 'is_working')
    op.drop_column('vr_station', 'name')
    op.drop_column('ps_station', 'is_working')
    op.drop_column('ps_station', 'name')
    op.drop_column('pc_station', 'is_working')
    op.drop_column('pc_station', 'name')
    # ### end Alembic commands ###
